# build.yaml

targets:
  $default:
    builders:
      l10n_mapper_generator:l10n_mapper_builder:
        enabled: true
        generate_for:
          - lib/l10n/app_localizations.dart
        options:
          l10n: true
          locale: true
          parseL10n: true
          message: "Translation key not found!"
          classNames: "AppLocalizations"
